// Trust Endpoints
export const statusUrl = "api/trust/status/"
export const setUpUrl = "api/trust/set-up/"
export const furtherRepairUrl = "api/trust/further-repair/"
export const trustUrl = "api/trust/trust/"
export const ownershipUrl = "api/trust/ownership/"
export const familyHistoryUrl = "api/trust/family-history/"
export const marketingHistoryUrl = "api/trust/marketing-history/"
export const marketingReportUrl = "api/trust/marketing-report/"
export const billsUrl = "api/accounting/bills/"

export const imagesUrl = "api/image/images/"
export const trustChatterUrl = "api/chatter/"
export const trustKanbanUrl = "api/trust/trust-kanban/"
export const trustDetailUrl = "api/trust/trust-detail/"
export const trustFormUrl = "api/trust/trust-form/"
export const trustRtpUrl = "api/trust/trust-rtp/"
export const trustTabUrl = "api/trust/trust-tabs/"
export const trustImportUrl = "api/trust/trust-import/"

//Address Endpoints
export const addressUrl = "api/address/address/"

// Contact Endpoints
export const pistatusUrl = "api/contact/pi-status/"
export const subcontactUrl = "api/contact/subcontact/"
export const subcontactDetailUrl = "api/contact/subcontact-detail/"
export const subcontactFormUrl = "api/contact/subcontact-form/"
export const contactUrl = "api/contact/contact/"
export const contactHistory="api/contact/contact-history/"
export const tagsUrl = "api/contact/tags/"
export const leadUrl = "api/contact/lead/"
export const familyUrl = "api/contact/family/"
export const walletUrl = "api/contact/wallet/"
export const hbcUrl = "api/contact/hbc/"
export const investorUrl = "api/contact/investor/"
export const contactDocumentsUrl = "api/contact/document/"
export const contactImagesUrl = "api/contact/image/"
export const contactChatterUrl = "api/contact/chatter/"
export const contactKanbanUrl = "api/contact/contact-kanban/"
export const contactDetail = "api/contact/contact-detail/"
export const contactForm="api/contact/contact-form/"

export const contactVendor = "api/contact/vendor/"
//Chatter Endpoints
export const chatterUrl = "api/chatter/chatter/"

//Chatter Endpoints
export const documentsUrl = "api/document/document/"
export const documentsTypeUrl = "api/document/document-type/"

export const familyLeadUrl="api/contact/family-lead/"
export const familyLeadSetupUrl="/api/contact/family-lead-stage/"

export const investorLeadUrl="api/contact/investor-lead/"
export const investorLeadSetupUrl="/api/contact/investor-lead-stage/"
export const publicUrl="/api/trust/public-home/"
export const trustSituationUrl = "api/trust/situations/"
export const trustSituationTagsUrl="api/trust/situation-tags/"
export const todosUrl="/api/todo/todo/"
export const accountingUrl="/api/accounting/plaid-link-token/"
export const accountingPublicApi="/api/accounting/plaid-access-token/"
export const userUrls="/api/account/user/"
export const employeesUrl="/api/account/employees/"
export const emailTemplateVariablesNameUrl="/api/templates/aviailable-fields/"
export const emailTemplateUrl="/api/templates/template/"